# Generated by Django 5.0 on 2024-07-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threat", "0002_alter_devicesvariations_device_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicesvariations",
            name="device_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="threat.devices",
                to_field="device_name",
            ),
        ),
    ]
